post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbml2IiwiaWQiOiI1ZWMyZTI4OTk2NWQ3MTM3Nzg1NjZiODMiLCJpYXQiOjE1ODk4MzAzNDN9.ZwcZziT64hMkI9Lm8DWepNbjvp5Iw3sBP9aYlQKypvg

{
    "title": "Mahtavaa menoa",
    "author": "Joka Mies",
    "url": "www.netti.fi",
    "likes": 1
}